# builder
FROM golang:1.24 AS builder

WORKDIR /src/

COPY go.mod go.sum ./
COPY . ./

RUN CGO_ENABLED=0 \
    GOOS=linux \
    go build -o discovery cmd/discovery/discovery.go

# runner
FROM alpine:latest@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
LABEL source_repository="https://github.com/sapcc/cni-nanny"

WORKDIR /

COPY --from=builder /src/discovery /discovery
ENTRYPOINT ["/discovery"]
