# permissions for end users to view bgppeerdiscoveries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bgppeerdiscovery-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cni-nanny
    app.kubernetes.io/part-of: cni-nanny
    app.kubernetes.io/managed-by: kustomize
  name: bgppeerdiscovery-viewer-role
rules:
- apiGroups:
  - bgp.cninanny.sap.cc
  resources:
  - bgppeerdiscoveries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bgp.cninanny.sap.cc
  resources:
  - bgppeerdiscoveries/status
  verbs:
  - get
