---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bgp.cninanny.sap.cc
  resources:
  - bgppeerdiscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bgp.cninanny.sap.cc
  resources:
  - bgppeerdiscoveries/finalizers
  verbs:
  - update
- apiGroups:
  - bgp.cninanny.sap.cc
  resources:
  - bgppeerdiscoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - topology.cninanny.sap.cc
  resources:
  - labeldiscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.cninanny.sap.cc
  resources:
  - labeldiscoveries/finalizers
  verbs:
  - update
- apiGroups:
  - topology.cninanny.sap.cc
  resources:
  - labeldiscoveries/status
  verbs:
  - get
  - patch
  - update
