//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredTopologyValue) DeepCopyInto(out *DiscoveredTopologyValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredTopologyValue.
func (in *DiscoveredTopologyValue) DeepCopy() *DiscoveredTopologyValue {
	if in == nil {
		return nil
	}
	out := new(DiscoveredTopologyValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelDiscovery) DeepCopyInto(out *LabelDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelDiscovery.
func (in *LabelDiscovery) DeepCopy() *LabelDiscovery {
	if in == nil {
		return nil
	}
	out := new(LabelDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LabelDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelDiscoveryList) DeepCopyInto(out *LabelDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LabelDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelDiscoveryList.
func (in *LabelDiscoveryList) DeepCopy() *LabelDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(LabelDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LabelDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelDiscoverySpec) DeepCopyInto(out *LabelDiscoverySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelDiscoverySpec.
func (in *LabelDiscoverySpec) DeepCopy() *LabelDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(LabelDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelDiscoveryStatus) DeepCopyInto(out *LabelDiscoveryStatus) {
	*out = *in
	if in.DiscoveredTopologyValues != nil {
		in, out := &in.DiscoveredTopologyValues, &out.DiscoveredTopologyValues
		*out = make(map[string]DiscoveredTopologyValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelDiscoveryStatus.
func (in *LabelDiscoveryStatus) DeepCopy() *LabelDiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(LabelDiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}
