//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredTopologyValue) DeepCopyInto(out *DiscoveredTopologyValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredTopologyValue.
func (in *DiscoveredTopologyValue) DeepCopy() *DiscoveredTopologyValue {
	if in == nil {
		return nil
	}
	out := new(DiscoveredTopologyValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelDiscovery) DeepCopyInto(out *LabelDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelDiscovery.
func (in *LabelDiscovery) DeepCopy() *LabelDiscovery {
	if in == nil {
		return nil
	}
	out := new(LabelDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LabelDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelDiscoveryList) DeepCopyInto(out *LabelDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LabelDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelDiscoveryList.
func (in *LabelDiscoveryList) DeepCopy() *LabelDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(LabelDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LabelDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelDiscoverySpec) DeepCopyInto(out *LabelDiscoverySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelDiscoverySpec.
func (in *LabelDiscoverySpec) DeepCopy() *LabelDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(LabelDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelDiscoveryStatus) DeepCopyInto(out *LabelDiscoveryStatus) {
	*out = *in
	if in.DiscoveredTopologyValues != nil {
		in, out := &in.DiscoveredTopologyValues, &out.DiscoveredTopologyValues
		*out = make(map[string]DiscoveredTopologyValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelDiscoveryStatus.
func (in *LabelDiscoveryStatus) DeepCopy() *LabelDiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(LabelDiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}
